// resources/js/Pages/Cart.vue
<template>
    <div>
        <div class="relative mr-1">
            <button id="cart" class="flex flex-row cursor-pointer truncate p-2 px-4 rounded">
                <div></div>
                <div @click="cartOpen = !cartOpen" class="flex flex-row-reverse ml-2 w-full text-gray-400 hover:text-gray-800 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500">
                    <div slot="icon" class="relative">
                        <div class="absolute text-xs rounded-full -mt-1 -mr-2 px-1 font-bold top-0 right-0 bg-red-700 text-white">30</div>
                        <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart w-6 h-6 mt-2">
                            <circle cx="9" cy="21" r="1"></circle>
                            <circle cx="20" cy="21" r="1"></circle>
                            <path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path>
                        </svg>
                    </div>
                </div>
            </button>
            <div v-if="cartOpen" class="absolute w-full rounded-b border-t-0 z-10">
                <div class="shadow-xl w-64">
                    <div class="p-2 flex bg-white hover:bg-gray-100 cursor-pointer border-b border-gray-100" style="">
                        X
                        <!--                                            <div class="p-2 w-12"><img src="https://dummyimage.com/50x50/bababa/0011ff&amp;text=50x50" alt="img product"></div>-->
                        <!--                                            <div class="flex-auto text-sm w-32">-->
                        <!--                                                <div class="font-bold">Product 1</div>-->
                        <!--                                                <div class="truncate">Product 1 description</div>-->
                        <!--                                                <div class="text-gray-400">Qt: 2</div>-->
                        <!--                                            </div>-->
                        <!--                                            <div class="flex flex-col w-18 font-medium items-end">-->
                        <!--                                                <div class="w-4 h-4 mb-6 hover:bg-red-200 rounded-full cursor-pointer text-red-700">-->
                        <!--                                                    <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2 ">-->
                        <!--                                                        <polyline points="3 6 5 6 21 6"></polyline>-->
                        <!--                                                        <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>-->
                        <!--                                                        <line x1="10" y1="11" x2="10" y2="17"></line>-->
                        <!--                                                        <line x1="14" y1="11" x2="14" y2="17"></line>-->
                        <!--                                                    </svg>-->
                        <!--                                                </div>-->
                        <!--                                                $12.22</div>-->
                    </div>
                    <div class="p-2 flex bg-white hover:bg-gray-100 cursor-pointer border-b border-gray-100" style="">
                        Y
                        <!--                                            <div class="p-2 w-12"><img src="https://dummyimage.com/50x50/bababa/0011ff&amp;text=50x50" alt="img product"></div>-->
                        <!--                                            <div class="flex-auto text-sm w-32">-->
                        <!--                                                <div class="font-bold">Product 2</div>-->
                        <!--                                                <div class="truncate">Product 2 long description</div>-->
                        <!--                                                <div class="text-gray-400">Qt: 2</div>-->
                        <!--                                            </div>-->
                        <!--                                            <div class="flex flex-col w-18 font-medium items-end">-->
                        <!--                                                <div class="w-4 h-4 mb-6 hover:bg-red-200 rounded-full cursor-pointer text-red-700">-->
                        <!--                                                    <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2 ">-->
                        <!--                                                        <polyline points="3 6 5 6 21 6"></polyline>-->
                        <!--                                                        <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>-->
                        <!--                                                        <line x1="10" y1="11" x2="10" y2="17"></line>-->
                        <!--                                                        <line x1="14" y1="11" x2="14" y2="17"></line>-->
                        <!--                                                    </svg>-->
                        <!--                                                </div>-->
                        <!--                                                $12.22</div>-->
                    </div>
                    <div class="p-2 flex bg-white hover:bg-gray-100 cursor-pointer border-b border-gray-100" style="">
                        Z
                        <!--                                            <div class="p-2 w-12"><img src="https://dummyimage.com/50x50/bababa/0011ff&amp;text=50x50" alt="img product"></div>-->
                        <!--                                            <div class="flex-auto text-sm w-32">-->
                        <!--                                                <div class="font-bold">Product 3</div>-->
                        <!--                                                <div class="truncate">Product 3 description</div>-->
                        <!--                                                <div class="text-gray-400">Qt: 2</div>-->
                        <!--                                            </div>-->
                        <!--                                            <div class="flex flex-col w-18 font-medium items-end">-->
                        <!--                                                <div class="w-4 h-4 mb-6 hover:bg-red-200 rounded-full cursor-pointer text-red-700">-->
                        <!--                                                    <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2 ">-->
                        <!--                                                        <polyline points="3 6 5 6 21 6"></polyline>-->
                        <!--                                                        <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>-->
                        <!--                                                        <line x1="10" y1="11" x2="10" y2="17"></line>-->
                        <!--                                                        <line x1="14" y1="11" x2="14" y2="17"></line>-->
                        <!--                                                    </svg>-->
                        <!--                                                </div>-->
                        <!--                                                $12.22</div>-->
                    </div>
                    <div class="p-4 justify-center flex">
                        <button class="text-base undefined hover:scale-110 focus:outline-none flex justify-center px-4 py-2 rounded font-bold cursor-pointer hover:bg-teal-700 hover:text-teal-100 bg-teal-100 text-teal-700 border duration-200 ease-in-out
                                            border-teal-600 transition">Checkout $36.66</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        name: "Cart",

        props: {
            cartOpen: Boolean,
        },
        data() {
            return {
                cartOpen: false,
            }
        },
    }
</script>

<style scoped>

</style>

// resources/js/Components/cart/index.jsx
import React from 'react'
import List from './list'

function Cart({ isCartOpen,setCartOpen,cartItems,checkOut}) {

    let sub_total = 0;

    const closeCart = ()=>{
        setCartOpen(false)
    }

    return (
        <div className= {isCartOpen?'relative z-10':'relative z-10 hidden'} aria-labelledby="slide-over-title" role="dialog" aria-modal="true">
                    
            <div className="fixed inset-0 bg-gray-500/75 transition-opacity" aria-hidden="true"></div>

            <div className="fixed inset-0 overflow-hidden">
                <div className="absolute inset-0 overflow-hidden">
                <div className="pointer-events-none fixed inset-y-0 right-0 flex max-w-full pl-10">
                
                    <div className="pointer-events-auto w-screen max-w-md">
                    <div className="flex h-full flex-col overflow-y-scroll bg-white shadow-xl">
                        <div className="flex-1 overflow-y-auto px-4 py-6 sm:px-6">
                        <div className="flex items-start justify-between">
                            <h2 className="text-lg font-medium text-gray-900" id="slide-over-title">Shopping cart</h2>
                            <div className="ml-3 flex h-7 items-center">
                            <button type="button" className="relative -m-2 p-2 text-gray-400 hover:text-gray-500" onClick={closeCart}>
                                <span className="absolute -inset-0.5"></span>
                                <span className="sr-only">Close panel</span>
                                <svg className="size-6" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
                                <path strokeLinecap="round" strokeLinejoin="round" d="M6 18 18 6M6 6l12 12" />
                                </svg>
                            </button>
                            </div>
                        </div>

                        <div className="mt-8">
                            <div className="flow-root">
                            <ul role="list" className="-my-6 divide-y divide-gray-200">
                                {cartItems.length > 0 &&
                                    cartItems.map((item,i) => {
                                    sub_total +=  item.product.price * item.quantity;
                                    if (i + 1 === item.length) {
                                        console.log(sub_total) 
                                     }
                                    return (     
                                        <List item={item} key={item.id} sub_total={sub_total}/>    
                                    )
                                })}
                            </ul>  
                            </div>
                        </div>
                        </div>

                        <div className="border-t border-gray-200 px-4 py-6 sm:px-6">
                        <div className="flex justify-between text-base font-medium text-gray-900">
                            <p>Subtotal</p>
                            <p>RM {sub_total.toFixed(2)}</p>
                        </div>
                        
                        <div className="mt-6">
                            <button className="w-full items-center justify-center rounded-md border border-transparent bg-indigo-600 px-6 py-3 text-base font-medium text-white shadow-xs hover:bg-indigo-700" onClick={checkOut}>Checkout</button>
                        </div>
                        <div className="mt-6 flex justify-center text-center text-sm text-gray-500">
                            <p>
                            or
                            <button type="button" className="font-medium text-indigo-600 hover:text-indigo-500" onClick={closeCart}>
                                Continue Shopping
                                <span aria-hidden="true"> &rarr;</span>
                            </button>
                            </p>
                        </div>
                        </div>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
    )
}

export default Cart
